# Generated by Django 4.0.3 on 2022-04-01 20:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameModel(
            old_name='Adresler',
            new_name='AdreslerModel',
        ),
        migrations.RenameModel(
            old_name='Orders',
            new_name='OrdersModel',
        ),
        migrations.RenameModel(
            old_name='Urunler',
            new_name='UrunlerModel',
        ),
    ]
