# Generated by Django 4.0.3 on 2022-04-01 20:42

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_kategorimodel_rename_adresler_adreslermodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategorimodel',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='degisecek', editable=False, populate_from='isim', unique=True),
        ),
        migrations.AlterField(
            model_name='kategorimodel',
            name='isim',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
