# Generated by Django 4.0.3 on 2022-04-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0004_alter_kategorimodel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='urunlermodel',
            name='kategoriler',
            field=models.ManyToManyField(related_name='urunler', to='commerce.kategorimodel'),
        ),
    ]
