# Generated by Django 4.0.3 on 2022-04-03 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0005_urunlermodel_kategoriler'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adreslermodel',
            options={'verbose_name': 'Adress', 'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='kategorimodel',
            options={'verbose_name': 'Kategori', 'verbose_name_plural': 'Kategoriler'},
        ),
        migrations.AlterModelTable(
            name='adreslermodel',
            table='Adress',
        ),
        migrations.AlterModelTable(
            name='kategorimodel',
            table='Kategori',
        ),
    ]
