# Generated by Django 4.0.3 on 2022-04-03 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commerce', '0006_alter_adreslermodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adreslermodel',
            options={'verbose_name': 'Adres', 'verbose_name_plural': 'Adresler'},
        ),
        migrations.AlterField(
            model_name='adreslermodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adres', to=settings.AUTH_USER_MODEL),
        ),
    ]
