# Generated by Django 4.0.3 on 2022-04-03 16:05

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0007_alter_adreslermodel_options_alter_adreslermodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='urunlermodel',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=1, editable=False, populate_from='baslik', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='urunlermodel',
            name='resim',
            field=models.ImageField(upload_to='urun_resimleri'),
        ),
    ]
