# Generated by Django 4.0.3 on 2022-04-03 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0008_urunlermodel_slug_alter_urunlermodel_resim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kategorimodel',
            name='slug',
        ),
    ]
