# Generated by Django 4.0.3 on 2022-04-03 16:06

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0010_kategorimodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kategorimodel',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='isim', unique=True),
        ),
    ]
