# Generated by Django 4.0.3 on 2022-04-03 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0011_alter_kategorimodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kategorimodel',
            name='isim',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
