# Generated by Django 4.0.3 on 2022-04-04 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0014_yorummodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='urunlermodel',
            name='price',
            field=models.FloatField(default=1),
        ),
    ]
