# Generated by Django 4.0.3 on 2022-04-04 22:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0015_urunlermodel_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersmodel',
            name='duzenlenme_tarihi',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ordersmodel',
            name='olusturulma_tarihi',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='urunlermodel',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='urunlermodel',
            name='price',
            field=models.FloatField(),
        ),
    ]
