# Generated by Django 4.0.3 on 2022-04-07 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commerce', '0016_ordersmodel_duzenlenme_tarihi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SepetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('urun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerce.urunlermodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sepet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'sepet',
                'verbose_name_plural': 'Sepet',
                'db_table': 'sepet',
            },
        ),
    ]
