# Generated by Django 4.0.3 on 2022-04-07 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0017_sepetmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sepetmodel',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
