# Generated by Django 4.0.3 on 2022-04-07 21:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commerce', '0018_alter_sepetmodel_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sepetmodel',
            name='user',
        ),
        migrations.AddField(
            model_name='sepetmodel',
            name='user',
            field=models.ManyToManyField(related_name='sepet', to=settings.AUTH_USER_MODEL),
        ),
    ]
