# Generated by Django 4.0.3 on 2022-04-08 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commerce', '0020_remove_sepetmodel_user_sepetmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sepetmodel',
            name='user',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sepet', to=settings.AUTH_USER_MODEL),
        ),
    ]
