# Generated by Django 4.0.3 on 2022-04-22 13:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0024_alter_ordersmodel_being_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='yorummodel',
            name='limited_integer_field',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
