# Generated by Django 4.0.3 on 2022-04-22 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0028_alter_yorummodel_limited_integer_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yorummodel',
            name='yorum',
            field=models.TextField(blank=True, null=True),
        ),
    ]
