# Generated by Django 4.0.4 on 2022-05-18 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0031_denemeadres_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='denemeadres',
            name='neighborhood',
            field=models.CharField(default='--', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='denemeadres',
            name='district',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='denemeadres',
            name='province',
            field=models.CharField(max_length=150),
        ),
    ]
