# Generated by Django 4.0.4 on 2022-05-25 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0033_denemeadres_default'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DenemeAdres',
        ),
    ]
