# Generated by Django 4.0.4 on 2022-05-25 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commerce', '0034_delete_denemeadres'),
    ]

    operations = [
        migrations.CreateModel(
            name='DenemeAdres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='s', max_length=150)),
                ('province', models.CharField(max_length=150)),
                ('district', models.CharField(max_length=150)),
                ('neighborhood', models.CharField(max_length=150)),
                ('short_description', models.TextField(max_length=150)),
                ('zip', models.CharField(max_length=100)),
                ('adress_type', models.CharField(choices=[('B', 'Billing'), ('S', 'Shipping')], max_length=1)),
                ('default', models.BooleanField(default=False)),
                ('tel', phonenumber_field.modelfields.PhoneNumberField(default='+905435040968', max_length=128, region=None)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adres2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
